### ISSUE TITLE
Error: apps/wcm-io/caconfig/editor/clientlibs/io.wcm.caconfig.editor.min.js:1079:30: ERROR - [JSC_LANGUAGE_FEATURE] This language feature is only supported for ECMASCRIPT_2020 mode or better: Optional chaining.

### ISSUE THREAD

**Issue by kwin** [wcm-io/io.wcm.caconfig.editor#82]
Currently the clientlib is compiled with level `ECMASCRIPT_2015` in https://github.com/wcm-io/io.wcm.caconfig.editor/blob/63e0e87a7b2daa0237af0d43a9b32fe3c2e0ae09/bundle/src/main/webapp/app-root/clientlibs/io.wcm.caconfig.editor.json#L12. However it uses [optional chaining](https://dev.to/richardburd/optional-chaining-in-javascript-es2020-illustrated-319d) e.g. in https://github.com/wcm-io/io.wcm.caconfig.editor/blob/63e0e87a7b2daa0237af0d43a9b32fe3c2e0ae09/bundle/src/main/webapp/app-root/clientlibs/io.wcm.caconfig.editor/js/editor/editor.module.js#L60 which is not supported until `ECMASCRIPT_2020`. 

That leads to the following error message when processing the clientlib with GCC:

```
[2026/09/23 11:13:52.634] [SEVERE] com.adobe.granite.clientlibs.compiler.gcc.impl.GCCLogErrorManager - apps/wcm-io/caconfig/editor/clientlibs/io.wcm.caconfig.editor.min.js:1079:30: ERROR - [JSC_LANGUAGE_FEATURE] This language feature is only supported for ECMASCRIPT_2020 mode or better: Optional chaining.
    const currentController = current?.$$route?.controller;
                              ^

[2026/09/23 11:13:52.634] [SEVERE] com.adobe.granite.clientlibs.compiler.gcc.impl.GCCLogErrorManager - apps/wcm-io/caconfig/editor/clientlibs/io.wcm.caconfig.editor.min.js:1080:30: ERROR - [JSC_LANGUAGE_FEATURE] This language feature is only supported for ECMASCRIPT_2020 mode or better: Optional chaining.
    const currentConfigName = current?.pathParams?.configName;
                              ^

[2026/09/23 11:13:52.635] [SEVERE] com.adobe.granite.clientlibs.compiler.gcc.impl.GCCLogErrorManager - apps/wcm-io/caconfig/editor/clientlibs/io.wcm.caconfig.editor.min.js:1081:27: ERROR - [JSC_LANGUAGE_FEATURE] This language feature is only supported for ECMASCRIPT_2020 mode or better: Optional chaining.
    const nextController = next?.$$route?.controller;
                           ^

[2026/09/23 11:13:52.635] [SEVERE] com.adobe.granite.clientlibs.compiler.gcc.impl.GCCLogErrorManager - apps/wcm-io/caconfig/editor/clientlibs/io.wcm.caconfig.editor.min.js:1082:27: ERROR - [JSC_LANGUAGE_FEATURE] This language feature is only supported for ECMASCRIPT_2020 mode or better: Optional chaining.
    const nextConfigName = next?.pathParams?.configName;
                           ^

[2026/09/23 11:13:52.635] [WARNING] com.adobe.granite.clientlibs.compiler.gcc.impl.GCCLogErrorManager - 4 error(s), 0 warning(s)
```

**Comment by kwin** [comment]
This is a regression introduced with https://github.com/wcm-io/io.wcm.caconfig.editor/commit/0aa302c53ca8d951df537061e7933f8e62b938b0.

**Comment by stefanseifert** [comment]
good point, fixed with #83

**Comment by kwin** [comment]
@stefanseifert Thanks for the quick fix, may be worth checking at Maven build time as well with https://github.com/blutorange/closure-compiler-maven-plugin to prevent regressions in the future.
